Added flag enums support
reagento/adaptix pull request #220
Opened 2024-01-20 09:47 UTC by daler-sz

2024-01-21 07:39 UTC, zhPavel requested changes

2024-01-21 07:39 UTC, zhPavel commented on src/adaptix/_internal/morphing/load_error.py
> +class MultipleBadVariantError(LoadError):
New exception naming policy suppose that name signaling error shouldn't have ``Error`` suffix.
Old exception will be renamed. It's ok that name of new exception is inconsistent with old one.

2024-01-21 07:39 UTC, zhPavel commented on src/adaptix/_internal/morphing/load_error.py
> +    input_values: Iterable[Any]
All ``LoadError`` must have ``input_value: Any`` field (not ``input_values``). Maybe for this case it can have ``Iterable[Any]`` type

2024-01-21 07:39 UTC, zhPavel commented on src/adaptix/_internal/morphing/enum_provider.py
> +def _extract_common_cases_from_flag(enum: Type[Flag]) -> Iterable[Flag]:
In the rest of the code such flag cases name ``compound``

2024-01-21 07:39 UTC, zhPavel commented on src/adaptix/_internal/morphing/enum_provider.py
> +    return result
I think that list comprehension will be look nice here

2024-01-21 07:39 UTC, zhPavel commented on src/adaptix/_internal/morphing/enum_provider.py
> +        return partial(self._flag_loader, enum=enum)
Returning partial will hold reference to provider, this prevents from producing standalone file with loader (file that knows nothing about retorts, this is planned feature).
Also permanent lookup through self attributes slow down code.

Loader should be closure capturing variables storing self atrributes

2024-01-21 08:19 UTC, daler-sz commented on src/adaptix/_internal/morphing/enum_provider.py
> +    def _flag_loader(self, data: Union[int, Iterable[Union[int, str]]], enum: Type[Flag]) -> Flag:
this typehint is wrong. should be `Union[int, Iterable[int], Iterable[str]]`

2024-01-22 17:51 UTC, zhPavel requested changes

2024-01-22 17:51 UTC, zhPavel commented on src/adaptix/_internal/morphing/enum_provider.py
> +                )
Generated loader should not hold references to provider (should not use ``self``)

2024-01-22 17:51 UTC, zhPavel commented on src/adaptix/_internal/morphing/enum_provider.py
> +                    msg=f"Duplicates in {enum} loader are not allowed",
API user knows nothing about what loader and enum class is it. Also I think it should be separate error class like 
```python

@custom_exception
@dataclass(eq=False)
class DuplicatedValues:
    input_value: Any
```

2024-01-22 17:51 UTC, zhPavel commented on src/adaptix/_internal/morphing/enum_provider.py
> +            return [mapping[case] for case in cases if case in value]
Is special case for non-compound value worth it?

2024-01-22 18:00 UTC, daler-sz commented on src/adaptix/_internal/morphing/enum_provider.py
> +            process_data = self._get_loader_process_data(data, enum)
The problem is that the linter complains about cognitive complexity

2024-01-22 19:37 UTC, zhPavel commented on src/adaptix/_internal/morphing/enum_provider.py
> +            process_data = self._get_loader_process_data(data, enum)
Supress the linter error)

2024-01-23 14:20 UTC, daler-sz commented on src/adaptix/_internal/morphing/enum_provider.py
> +            process_data = list(data)
I don't understand this snippet. Firstly, it seems to me that you forgot some `not`'s. Secondly, why we should check type with `type`, shouldn't we interpret all string subtypes as single values?

2024-01-23 18:09 UTC, zhPavel commented on src/adaptix/_internal/morphing/enum_provider.py
> +            process_data = list(data)
In fact, builtin loader exclude str from Iterable only if strinct_coercion is enabled. But I don’t see the point in considering in this case that str is also an Iterable, regardless of strcit_coercion

2024-01-25 20:54 UTC, zhPavel requested changes

2024-01-25 20:54 UTC, zhPavel commented on src/adaptix/_internal/morphing/enum_provider.py
> +            else:
There is common policy prevent interpreting dict as iterable of strings if strict_coercion is True

2024-01-25 20:54 UTC, zhPavel commented on src/adaptix/_internal/morphing/enum_provider.py
> +            return enum(data)
A comment is needed here that would explain that the data has already been validated and the enum cannot raise an error

2024-01-25 20:54 UTC, zhPavel commented on src/adaptix/_internal/morphing/enum_provider.py
> +                raise OutOfRange(0, flag_mask, data)
Operators precedence are not obvious at this case. Something like ``data < 0 or data > flag_mask`` would be more straightforward

2024-01-25 20:54 UTC, zhPavel commented on src/adaptix/_internal/morphing/facade/retort.py
>          EnumExactValueProvider(),  # it has higher priority than scalar types for Enum with mixins
I think that using high-level factories here shouble become a standard (``flag_by_exact_value`` and ``enum_by_exact_value``)

2024-01-25 20:54 UTC, zhPavel commented on tests/unit/morphing/test_enum_provider.py
> +    )
Need tests with data of bad type (string, list, dict, None)

2024-01-25 20:54 UTC, zhPavel commented on tests/unit/morphing/test_enum_provider.py
> +    assert loader(["CASE_ONE", "CASE_FOUR"]) == FlagEnum.CASE_ONE | FlagEnum.CASE_FOUR
Need tests with data of bad type (string, int, dict, None)

2024-01-25 21:08 UTC, zhPavel commented
The feature looks almost complete. But there is need a documentation at specific-types-behavior.rst file and docstring of high-level factory ``flag_by_list_using_name`` should contain desctiprion of limitations.

It is also necessary to add a fragment of the changelog with a description of the new feature.
You can find instruction to creating such fragments in docs/changelog/fragments/README.rst

2024-01-26 15:19 UTC, zhPavel requested changes

2024-01-26 15:39 UTC, zhPavel approved these changes

2024-01-26 15:40 UTC, merged