Feature/sqlite bench
reagento/adaptix pull request #354
Opened 2024-12-26 11:07 UTC by close2code-palm

Code related to #307

2025-01-01 22:37 UTC, zhPavel requested changes

2025-01-01 22:37 UTC, zhPavel commented on benchmarks/benchmarks/bench_nexus.py
> +                operator.fill_validation(dist_to_versions)
Extracting data from pyperf report does not belong to layer of report storing. You can use load_benchmarks method to get all reports

2025-01-01 22:37 UTC, zhPavel commented on benchmarks/benchmarks/pybench/persistence/common.py
> +        raise NotImplementedError
Where is this method used inside operators?

2025-01-01 22:37 UTC, zhPavel commented on benchmarks/benchmarks/pybench/persistence/common.py
> +from mypy.memprofile import defaultdict
This is wrong import path

2025-01-01 22:37 UTC, zhPavel commented on benchmarks/benchmarks/pybench/persistence/common.py
> +        raise NotImplementedError
`Sequence` means that it returns sequence of any type, but this method returns sequence of dicts

2025-01-01 22:37 UTC, zhPavel commented on benchmarks/benchmarks/pybench/persistence/database.py
> +from sqlalchemy import Sequence
This is wrong import path

2025-01-01 22:37 UTC, zhPavel commented on benchmarks/benchmarks/pybench/persistence/database.py
> +import pysqlite3 as sqlite3
Module renaming is confusing

2025-01-01 22:37 UTC, zhPavel commented on benchmarks/benchmarks/pybench/persistence/common.py
> +        raise NotImplementedError
Structure of release data format should be independent from internal format using for work.
And we have no reasongs to change this release format

2025-01-01 22:37 UTC, zhPavel commented on benchmarks/benchmarks/pybench/director_api.py
> +        operator_class: type[BenchOperator],
It should be a factory, not a class. Constructor is not part of class interface

2025-01-03 21:56 UTC, zhPavel requested changes

2025-01-03 21:56 UTC, zhPavel commented on benchmarks/benchmarks/pybench/persistence/database.py
> +        return f"""Index not found - {self.hub_key}"""
This exception is never raised

2025-01-03 21:56 UTC, zhPavel commented on benchmarks/benchmarks/pybench/persistence/database.py
> +     bench(benchmark_name, benchmark_subname, global_id) WHERE is_actual=TRUE;"""
Why there are two query? Also, I think it will be more readable if start of query will be placed to new line

2025-01-03 21:56 UTC, zhPavel commented on benchmarks/benchmarks/pybench/persistence/database.py
> +        self.accessor = accessor
Why can accessor be equal to None?

2025-01-03 21:56 UTC, zhPavel commented on benchmarks/benchmarks/pybench/persistence/database.py
> +    ) VALUES (?,?,?,?,?,?,?,?,?,?,?);"""
I think it will be more readable if start of query will be placed to new line

2025-01-03 21:56 UTC, zhPavel commented on benchmarks/benchmarks/pybench/persistence/database.py
> +    ) VALUES (?,?,?,?,?,?,?,?,?,?,?);"""
Why is insert query separeted from other queries?

2025-01-03 21:56 UTC, zhPavel commented on benchmarks/benchmarks/pybench/persistence/database.py
> +    migrate_sqlite(DATABASE_FILE_NAME)
Why is this necessary?

2025-01-03 21:56 UTC, zhPavel commented on benchmarks/benchmarks/pybench/persistence/database.py
> +    def read_schemas_content(self) -> Sequence[str]:
Schema describes benchmark case. There is no content of schema. This method should be called like `read_benchmark_results`

2025-01-06 09:30 UTC, zhPavel requested changes

2025-01-06 09:30 UTC, zhPavel commented on benchmarks/benchmarks/pybench/persistence/common.py
> +        return
This methods returns the same entities, but in one case it named as  `bench_data` and in other case it names as `benchmarks_results`.

Term `benchmark data` is too common, it can means everything. So, I suggest to use `get_bench_result` and `get_all_bench_results`

2025-01-06 09:30 UTC, zhPavel commented on benchmarks/benchmarks/pybench/persistence/common.py
> +    pass
I think that separating to writer and reader is redudant here

2025-01-06 09:30 UTC, zhPavel commented on benchmarks/benchmarks/pybench/persistence/common.py
> +        raise NotImplementedError
Method `bench_result_file` should be part of FileSystemBenchOperator

2025-01-06 09:30 UTC, zhPavel commented on benchmarks/benchmarks/bench_nexus.py
> +
Releaser should use operator interface

2025-01-06 09:30 UTC, zhPavel commented on benchmarks/benchmarks/bench_nexus.py
> +                    for dist, version in json.loads(bench_report)["pybench_data"]["distributions"].items():
For consistrent namig you should use bench_result instead of bench_report

2025-01-06 09:30 UTC, zhPavel commented on benchmarks/benchmarks/pybench/persistence/database.py
> +        return data[0]
Why are there here custom exception?

2025-01-06 12:05 UTC, close2code-palm commented on benchmarks/benchmarks/pybench/persistence/database.py
> +     bench(benchmark_name, benchmark_subname, global_id) WHERE is_actual=TRUE;"""
SQLite can not use "execute" for multiple commands in single step.

2025-01-06 12:11 UTC, close2code-palm commented on benchmarks/benchmarks/pybench/director_api.py
> +        operator_factory: Callable[[BenchAccessor], BenchOperator],
For now, operators is created by methods injected with SQLite inside executor classes, and flag needs to be passed by user(invoker). Is it the right way?

2025-01-06 12:12 UTC, close2code-palm commented on benchmarks/benchmarks/pybench/persistence/database.py
> +def migrate_sqlite(database_name: str):
Named as database_initialization

2025-01-06 12:17 UTC, close2code-palm commented on benchmarks/benchmarks/pybench/persistence/database.py
> +    migrate_sqlite(DATABASE_FILE_NAME)
Without database initialization records cannot be placed into the storage, so we need to provide a possibility to prepare somehow. Also, you confirmed that code is in right place.

2025-01-06 12:21 UTC, close2code-palm commented on benchmarks/benchmarks/pybench/persistence/database.py
> +        return data[0]
I tried to make errors more descriptive, should I remove this? Index error will say nothing about what is missing, as SQL logs are not used

2025-01-08 11:12 UTC, zhPavel commented on benchmarks/benchmarks/pybench/persistence/database.py
> +     bench(benchmark_name, benchmark_subname, global_id) WHERE is_actual=TRUE;"""
What about https://docs.python.org/3/library/sqlite3.html#sqlite3.Cursor.executescript?

2025-01-08 11:15 UTC, zhPavel commented on benchmarks/benchmarks/pybench/persistence/database.py
> +    migrate_sqlite(DATABASE_FILE_NAME)
Is this file supposed to be executed directly?

2025-01-08 11:37 UTC, zhPavel requested changes

2025-01-08 11:37 UTC, zhPavel commented on benchmarks/benchmarks/pybench/persistence/common.py
> +        return
But you write more information than is in the bench results. BenchRecord consists of bench result + metadata. I think write_bench_record will be better there

2025-01-08 11:37 UTC, zhPavel commented on benchmarks/benchmarks/bench_nexus.py
> +                        release_zip.writestr(file_path.name, data)
This code looks very strange at the moment. At the beginning env_to_files is created, but then files is unused.
When you use sqlite to store data, there are no bench result files. As I said above, the bench_result_file method should go away from BenchAccessor.

2025-01-08 11:37 UTC, zhPavel commented on benchmarks/benchmarks/pybench/persistence/common.py
> +        return None
Adaptix uses convention that all abstact methods should have `...` as body

2025-01-08 11:38 UTC, zhPavel commented on benchmarks/benchmarks/nexus_utils.py
Why is this code moved to a separate file?

2025-01-15 18:49 UTC, zhPavel requested changes

2025-01-15 21:48 UTC, close2code-palm commented on benchmarks/benchmarks/pybench/persistence/database.py
> +    migrate_sqlite(DATABASE_FILE_NAME)
Yes, it is now supposed to be executed as module manually before any bench actions related to database as a part of preparation. It is possible to place it in Just initialization or to add a script somewhere

2025-01-25 16:20 UTC, zhPavel requested changes

2025-01-25 16:20 UTC, zhPavel commented on benchmarks/benchmarks/bench_nexus.py
> +                        self._release_from_sqlite(release_zip, bench_ids, bench_results)
This condition violates encapsutation of storage

2025-01-25 16:20 UTC, zhPavel commented on benchmarks/benchmarks/bench_nexus.py
> +                    )
`env_files` written to `index.json` consists of enviroment name and list of output result files. This mapping is actual for any type of working data storage

2025-01-25 16:24 UTC, zhPavel commented on benchmarks/benchmarks/pybench/persistence/common.py
> +        ...
Why `bench_exists` method is exists? You can use `get_bench_result` for this

2025-01-25 16:24 UTC, zhPavel commented on benchmarks/benchmarks/pybench/persistence/database.py
> +        return data[0]
This exception is raised only for internal error. It looks like it should be a private module member

2025-01-25 16:30 UTC, zhPavel commented on benchmarks/benchmarks/pybench/persistence/common.py
> +    created_at: datetime.datetime
It looks like `created_at` should be assigned by operator automatically

2025-01-25 16:30 UTC, zhPavel commented on benchmarks/benchmarks/pybench/persistence/common.py
> +    created_at: datetime.datetime
I think, it would be better to pass `kwargs`, `distributions` and `data` as dicts and lists (serialization is responsibility of operator).

Also, all these types should be stores as JSON insize SQLite

2025-03-09 12:34 UTC, merged